version: '3.3'
services:
  app:
    image: docker-set_information
    ports:
      - 8081:8081
    #network_mode: "host"
    build:
      context: .
    container_name: app_set
    networks:
      mynetwork:
        aliases:
          - app_set.mynetwork
networks:
  mynetwork:
    external:
      name: myglobalnetwork